name: Render Templates
description: Interpolates template strings

inputs:
  image-tag:
    description: "Image Tag"
    required: true
  deploy-color:
    description: "Deploy Color"
    required: true
  path:
    description: "Path to files"
    required: true


runs:
  using: 'composite'
  steps:
    - name: Render and display
      shell: bash
      run: |
        for file in ${{ inputs.path }}/*.yml; do
          [ -f "${file}" ] || break # Don't iterate over null
          echo "Rendering $file"
          sed -e 's/ENV_DEPLOY_COLOR/${{ inputs.deploy-color }}/g' -e 's/ENV_IMAGE_TAG/${{ inputs.image-tag }}/g' ${file} > ${file}.bak
          mv ${file}.bak ${file}
          cat ${file}
        done
